In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel("/flight_price.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [3]:
df.sample(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
6826,IndiGo,24/05/2019,Kolkata,Banglore,CCU → BLR,11:30,14:05,2h 35m,non-stop,No info,5224
2037,Vistara,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,07:10,09:05 07 Jun,25h 55m,1 stop,No info,8452
7004,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,13:00,15:50,2h 50m,non-stop,No info,8033
9024,Jet Airways,27/05/2019,Delhi,Cochin,DEL → AMD → BOM → COK,23:05,04:25 29 May,29h 20m,2 stops,No info,16704
9174,Jet Airways,21/03/2019,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678

In [4]:
df.shape

(10683, 11)

In [5]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [6]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [8]:
df.dropna(axis = 0, inplace = True)

In [9]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [10]:
df.shape

(10682, 11)

In [11]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [12]:
df['Date_of_Journey']

0        24/03/2019
1         1/05/2019
2         9/06/2019
3        12/05/2019
4        01/03/2019
            ...
10678     9/04/2019
10679    27/04/2019
10680    27/04/2019
10681    01/03/2019
10682     9/05/2019
Name: Date_of_Journey, Length: 10682, dtype: object

In [13]:
df["Date"]= df['Date_of_Journey'].str.split("/").str[0]
df["Month"]= df['Date_of_Journey'].str.split("/").str[1]
df["Year"]= df['Date_of_Journey'].str.split("/").str[2]
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,04,2019
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,04,2019
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,04,2019
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,01,03,2019
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,05,2019

In [14]:
df['Date']= df['Date'].astype(int)
df['Month']= df['Month'].astype(int)
df['Year']= df['Year'].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  object
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  object
 6   Arrival_Time     10682 non-null  object
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
 11  Date             10682 non-null  int64
 12  Month            10682 non-null  int64
 13  Year             10682 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.5+ MB

In [16]:
df.drop('Date_of_Journey', axis = 1 , inplace = True)

In [17]:
df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [18]:
df['Arrival_Time'].unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], dtype=object)

In [19]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [20]:
df["Arrival_Hr"]= df['Arrival_Time'].str.split(":").str[0]
df["Arrival_Mins"]= df['Arrival_Time'].str.split(":").str[1]

In [21]:
df["Arrival_Hr"] = df["Arrival_Hr"].astype(int)
df["Arrival_Mins"] = df["Arrival_Mins"].astype(int)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  Date             10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Year             10682 non-null  int64
 13  Arrival_Hr       10682 non-null  int64
 14  Arrival_Mins     10682 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.6+ MB

In [23]:
df.drop('Arrival_Time', axis = 1, inplace = True)

In [24]:
df

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hr,Arrival_Mins
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,2h 30m,non-stop,No info,4107,9,4,2019,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,2h 35m,non-stop,No info,4145,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,3h,non-stop,No info,7229,27,4,2019,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,2h 40m,non-stop,No info,12648,1,3,2019,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,8h 20m,2 stops,No info,11753,9,5,2019,19,15

In [25]:
df["Dep_hr"]=df['Dep_Time'].str.split(":").str[0]
df["Dep_min"]=df['Dep_Time'].str.split(":").str[1]

In [26]:
df["Dep_hr"]=df["Dep_hr"].astype(int)
df["Dep_min"]=df["Dep_min"].astype(int)

In [27]:
df.drop('Dep_Time', axis= 1, inplace= True)

In [28]:
df["Total_Stops"] = df["Total_Stops"].map({'non-stop':0,'1 stop':1, '2 stops':2, '3 stops':3,'4 stops':4})

In [29]:
df["Total_Stops"] = df["Total_Stops"].astype(int)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  int64
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   Date             10682 non-null  int64
 9   Month            10682 non-null  int64
 10  Year             10682 non-null  int64
 11  Arrival_Hr       10682 non-null  int64
 12  Arrival_Mins     10682 non-null  int64
 13  Dep_hr           10682 non-null  int64
 14  Dep_min          10682 non-null  int64
dtypes: int64(9), object(6)
memory usage: 1.6+ MB

In [31]:
df.drop("Route", axis = 1, inplace = True)

In [32]:
df['Duration_hrs'] = df['Duration'].str.split(" ").str[0].str.split('h').str[0]
df

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hr,Arrival_Mins,Dep_hr,Dep_min,Duration_hrs
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,2h 30m,0,No info,4107,9,4,2019,22,25,19,55,2
10679,Air India,Kolkata,Banglore,2h 35m,0,No info,4145,27,4,2019,23,20,20,45,2
10680,Jet Airways,Banglore,Delhi,3h,0,No info,7229,27,4,2019,11,20,8,20,3
10681,Vistara,Banglore,New Delhi,2h 40m,0,No info,12648,1,3,2019,14,10,11,30,2
10682,Air India,Delhi,Cochin,8h 20m,2,No info,11753,9,5,2019,19,15,10,55,8

In [33]:
mask = df['Duration_hrs'].str.contains('m', na=False)
df.loc[mask, 'Duration_mins'] = df.loc[mask, 'Duration_hrs'].str.replace('m', '', regex=True)
df.loc[mask, 'Duration_hrs'] = 0
df["Duration_hrs"].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', 0, '41', '40'], dtype=object)

In [34]:
df['Duration_mins'] = df['Duration'].str.split(" ").str[1].str.split('h').str[0]
df

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hr,Arrival_Mins,Dep_hr,Dep_min,Duration_hrs,Duration_mins
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50m
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25m
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,25m
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,45m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,2h 30m,0,No info,4107,9,4,2019,22,25,19,55,2,30m
10679,Air India,Kolkata,Banglore,2h 35m,0,No info,4145,27,4,2019,23,20,20,45,2,35m
10680,Jet Airways,Banglore,Delhi,3h,0,No info,7229,27,4,2019,11,20,8,20,3,NaN
10681,Vistara,Banglore,New Delhi,2h 40m,0,No info,12648,1,3,2019,14,10,11,30,2,40m
10682,Air India,Delhi,Cochin,8h 20m,2,No info,11753,9,5,2019,19,15,10,55,8,20m

In [35]:
df['Duration_mins']=df['Duration_mins'].str[0]

In [36]:
df['Duration_mins']=df['Duration_mins'].fillna(0)
df

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hr,Arrival_Mins,Dep_hr,Dep_min,Duration_hrs,Duration_mins
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,5
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,2
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,2
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,2h 30m,0,No info,4107,9,4,2019,22,25,19,55,2,3
10679,Air India,Kolkata,Banglore,2h 35m,0,No info,4145,27,4,2019,23,20,20,45,2,3
10680,Jet Airways,Banglore,Delhi,3h,0,No info,7229,27,4,2019,11,20,8,20,3,0
10681,Vistara,Banglore,New Delhi,2h 40m,0,No info,12648,1,3,2019,14,10,11,30,2,4
10682,Air India,Delhi,Cochin,8h 20m,2,No info,11753,9,5,2019,19,15,10,55,8,2

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Date             10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Arrival_Hr       10682 non-null  int64
 11  Arrival_Mins     10682 non-null  int64
 12  Dep_hr           10682 non-null  int64
 13  Dep_min          10682 non-null  int64
 14  Duration_hrs     10682 non-null  object
 15  Duration_mins    10682 non-null  object
dtypes: int64(9), object(7)
memory usage: 1.6+ MB

In [38]:
df["Duration_hrs"]=df["Duration_hrs"].astype(int)
df["Duration_mins"]=df["Duration_mins"].astype(int)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  int64
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   Date             10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Arrival_Hr       10682 non-null  int64
 11  Arrival_Mins     10682 non-null  int64
 12  Dep_hr           10682 non-null  int64
 13  Dep_min          10682 non-null  int64
 14  Duration_hrs     10682 non-null  int64
 15  Duration_mins    10682 non-null  int64
dtypes: int64(11), object(5)
memory usage: 1.6+ MB

In [40]:
df

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hr,Arrival_Mins,Dep_hr,Dep_min,Duration_hrs,Duration_mins
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,5
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,2
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,2
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,2h 30m,0,No info,4107,9,4,2019,22,25,19,55,2,3
10679,Air India,Kolkata,Banglore,2h 35m,0,No info,4145,27,4,2019,23,20,20,45,2,3
10680,Jet Airways,Banglore,Delhi,3h,0,No info,7229,27,4,2019,11,20,8,20,3,0
10681,Vistara,Banglore,New Delhi,2h 40m,0,No info,12648,1,3,2019,14,10,11,30,2,4
10682,Air India,Delhi,Cochin,8h 20m,2,No info,11753,9,5,2019,19,15,10,55,8,2